"""empty message

Revision ID: fb4d9046894b
Revises: 44184d6911f3
Create Date: 2024-09-19 08:10:06.300334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4d9046894b'
down_revision = '44184d6911f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camisetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talla', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaqueros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talla', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zapatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talla', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planets')
    op.drop_table('vehicles')
    op.drop_table('characters')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_name_key', type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_name_key', ['name'])

    op.create_table('characters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Birth_year', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('Eye_color', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('Films', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('Gender', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('Hair_color', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('Heigh', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('Homeworld', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('Mass', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('Skin_color', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('Created', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('Edited', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('Species', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('Starships', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('Url', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('Vehicles', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='characters_pkey'),
    sa.UniqueConstraint('Birth_year', name='characters_Birth_year_key'),
    sa.UniqueConstraint('Created', name='characters_Created_key'),
    sa.UniqueConstraint('Edited', name='characters_Edited_key'),
    sa.UniqueConstraint('Eye_color', name='characters_Eye_color_key'),
    sa.UniqueConstraint('Films', name='characters_Films_key'),
    sa.UniqueConstraint('Gender', name='characters_Gender_key'),
    sa.UniqueConstraint('Hair_color', name='characters_Hair_color_key'),
    sa.UniqueConstraint('Heigh', name='characters_Heigh_key'),
    sa.UniqueConstraint('Homeworld', name='characters_Homeworld_key'),
    sa.UniqueConstraint('Mass', name='characters_Mass_key'),
    sa.UniqueConstraint('Name', name='characters_Name_key'),
    sa.UniqueConstraint('Skin_color', name='characters_Skin_color_key'),
    sa.UniqueConstraint('Species', name='characters_Species_key'),
    sa.UniqueConstraint('Starships', name='characters_Starships_key'),
    sa.UniqueConstraint('Url', name='characters_Url_key'),
    sa.UniqueConstraint('Vehicles', name='characters_Vehicles_key')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Cargo_capacity', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('consumables', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('cost_in_credits', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('created', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('crew', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('edited', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('length', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('max_atmosphering_speed', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('passengers', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('pilots', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('films', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('vehicle_class', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='vehicles_pkey'),
    sa.UniqueConstraint('Cargo_capacity', name='vehicles_Cargo_capacity_key'),
    sa.UniqueConstraint('consumables', name='vehicles_consumables_key'),
    sa.UniqueConstraint('cost_in_credits', name='vehicles_cost_in_credits_key'),
    sa.UniqueConstraint('created', name='vehicles_created_key'),
    sa.UniqueConstraint('crew', name='vehicles_crew_key'),
    sa.UniqueConstraint('edited', name='vehicles_edited_key'),
    sa.UniqueConstraint('films', name='vehicles_films_key'),
    sa.UniqueConstraint('length', name='vehicles_length_key'),
    sa.UniqueConstraint('manufacturer', name='vehicles_manufacturer_key'),
    sa.UniqueConstraint('max_atmosphering_speed', name='vehicles_max_atmosphering_speed_key'),
    sa.UniqueConstraint('model', name='vehicles_model_key'),
    sa.UniqueConstraint('name', name='vehicles_name_key'),
    sa.UniqueConstraint('passengers', name='vehicles_passengers_key'),
    sa.UniqueConstraint('pilots', name='vehicles_pilots_key'),
    sa.UniqueConstraint('url', name='vehicles_url_key'),
    sa.UniqueConstraint('vehicle_class', name='vehicles_vehicle_class_key')
    )
    op.create_table('planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('climate', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('created', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('diameter', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('edited', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('films', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('gravity', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('orbital_period', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('population', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('residents', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('surface_water', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('terrain', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='planets_pkey'),
    sa.UniqueConstraint('climate', name='planets_climate_key'),
    sa.UniqueConstraint('created', name='planets_created_key'),
    sa.UniqueConstraint('diameter', name='planets_diameter_key'),
    sa.UniqueConstraint('edited', name='planets_edited_key'),
    sa.UniqueConstraint('films', name='planets_films_key'),
    sa.UniqueConstraint('gravity', name='planets_gravity_key'),
    sa.UniqueConstraint('name', name='planets_name_key'),
    sa.UniqueConstraint('orbital_period', name='planets_orbital_period_key'),
    sa.UniqueConstraint('population', name='planets_population_key'),
    sa.UniqueConstraint('residents', name='planets_residents_key'),
    sa.UniqueConstraint('surface_water', name='planets_surface_water_key'),
    sa.UniqueConstraint('terrain', name='planets_terrain_key'),
    sa.UniqueConstraint('url', name='planets_url_key')
    )
    op.drop_table('zapatos')
    op.drop_table('vaqueros')
    op.drop_table('camisetas')
    # ### end Alembic commands ###
